### PR TITLE
User profile delegation tab

### LINKED ISSUE #682: delegations on user profile
1. the user profile always has empty delegations.  this is suspicious, but i haven't looked into whether it's just missing demo data or whether there is something wrong with constructing or rendering it.
1. scope buttons should use the DScope selection widget from the network browser page.  (this may be a duplicate of another issue we've already open.)

### PR DESCRIPTION
**Pull request by fisx**
Fixes #682.

### CODE REVIEW

File: src/Frontend/Fragment/DelegationTab.hs [hunk 1]
```diff
@@ -34,9 +34,17 @@ renderDelegations (temporary -> delegations) = do
             div_ [class_ "col-11-12"] $ do
                 h3_ $ a_ [href_ $ U.viewUserProfile delegate]
                     (delegate ^. userLogin . unUserLogin  . html)
-                p_ $ do
-                    toHtml $ show (length delegatees) <> " Stimmen von "
-                    let f :: User -> HtmlT m ()
-                        f delegatee = strong_ $ a_ [href_ $ U.viewUserProfile delegatee]
-                            (delegatee ^. userLogin . unUserLogin  . html)
-                    sequence_ . intersperse ", " $ f <$> delegatees
+                case length delegatees of
```
Comment (fisx) [inline src/Frontend/Fragment/DelegationTab.hs]: introduce name for `length delegatees` and reuse.

File: src/Frontend/Fragment/DelegationTab.hs [hunk 2]
```diff
@@ -34,9 +34,17 @@ renderDelegations (temporary -> delegations) = do
...
+                    0 -> nil
+                    n -> do
+                        p_ $ do
+                            -- FUTUREWORK: we should name the voting power here, and then the list of
+                            -- delegatees.  (voting power is different from length of delegatee list unless
+                            -- the delegate has delegated to herself.)
+                            toHtml $ show (length delegatees)
```
Comment (fisx) [inline src/Frontend/Fragment/DelegationTab.hs]: no, wait.  this should just be `n`.

**Comment by andorp** [comment]
LGTM
